tp_smapi: add support for kernel 6.4
Changes due to kernel 6.4 commit
48380368dec ("Change DEFINE_SEMAPHORE() to take a number argument")

Fixes the following building errors:

/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/tp_smapi/thinkpad_ec.c:94:42: error: too few arguments provided to function-like macro invocation
static DEFINE_SEMAPHORE(thinkpad_ec_mutex);
                                         ^
...
/home/utente/r-x86_kernel/out/target/product/x86_64/obj/kmodule/tp_smapi/tp_smapi.c:115:36: error: too few arguments provided to function-like macro invocation
static DEFINE_SEMAPHORE(smapi_mutex);
                                   ^

Change-Id: I427d7182a52f9a5377994c4041cd82756e12f338