tp_smapi: add support for kernel 6.15
Changes due to kernel 6.15 commit
8fa7292fee5 "treewide: Switch/rename to timer_delete[_sync]()"

Fixes the followion building errors:

hdaps.c:430:2: error: call to undeclared function 'del_timer_sync'; ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
        del_timer_sync(&hdaps_timer);
        ^
hdaps.c:674:3: error: call to undeclared function 'del_timer_sync'; ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
                del_timer_sync(&hdaps_timer);
                ^
2 errors generated.

Change-Id: I7d929b9c815a5da9cc4a824b5618e93d117d7927